import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<body className="font-inter flex justify-center items-center min-h-screen bg-gradient-to-br h-screen from-[#3F4C91] to-[#C2AACB] ">

        <div className="p-8 bg-[#BDD0CF] rounded-xl shadow-2xl w-96">
        {children}
        </div>
       </body>
    </html>
  )
}